---
spring:
  profiles: default
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
          lob:
            non_contextual_creation: true
  session:
      store-type: none
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: elenuncaesquece
    url: jdbc:postgresql://localhost:5432/admin
    maxActive: 10
    maxIdle: 5
    minIdle: 2
    initialSize: 5
    removeAbandoned: true
    validateQuery: SELECT 1
    remove-abandoned: true
    test-while-idle: true
    remove-abandoned-timeout: 900
  flyway:
    enabled: true
server:
  port: 8181
cors:
  origins: http://localhost:3000
app:
  jwtSecret: JWTSuperSecretKey
  jwtExpirationInMs: 604800000

---
spring:
  profiles: homologation
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
          lob:
            non_contextual_creation: true
  session:
      store-type: none
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: elenuncaesquece
    url: jdbc:postgresql://localhost:5432/ea_api
    maxActive: 10
    maxIdle: 5
    minIdle: 2
    initialSize: 5
    removeAbandoned: true
    validateQuery: SELECT 1
    remove-abandoned: true
    test-while-idle: true
    remove-abandoned-timeout: 900
  flyway:
    enabled: true
server:
  port: 8181
cors:
  origins: http://localhost:3000
app:
  jwtSecret: JWTSuperSecretKey
  jwtExpirationInMs: 604800000

---
spring:
  profiles: production
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
          lob:
            non_contextual_creation: true
  session:
      store-type: none
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: elenuncaesquece
    url: jdbc:postgresql://localhost:5432/ea_api
    maxActive: 10
    maxIdle: 5
    minIdle: 2
    initialSize: 5
    removeAbandoned: true
    validateQuery: SELECT 1
    remove-abandoned: true
    test-while-idle: true
    remove-abandoned-timeout: 900
  flyway:
    enabled: true
server:
  port: 8181
cors:
  origins: http://localhost:3000
app:
  jwtSecret: JWTSuperSecretKey
  jwtExpirationInMs: 604800000
